# Configurações do Projeto
sonar.projectKey=seminario_qualidade_tema4
sonar.projectName=Seminario Qualidade - Tema 4
sonar.projectVersion=1.0

# Caminho dos fontes
sonar.sources=.
sonar.exclusions=**/__pycache__/**, **/.git/**

# Linguagem
sonar.language=py
sonar.python.version=3
sonar.sourceEncoding=UTF-8

# Host e Autenticação (Descomente e preencha se usar SonarCloud)
sonar.host.url=https://sonarcloud.io
sonar.organization=rayanneadjene
sonar.projectKey=rayanneadjene_seminario
# sonar.login=seu_token_aqui

# Se usar servidor local (SonarQube via Docker):
# sonar.host.url=http://localhost:9000
# sonar.login=admin
# sonar.password=admin
